import pytest
from unittest.mock import MagicMock
from src.retrieval.hybrid_search import AdvancedRetriever
from langchain_core.documents import Document
from src.retrieval.vector_store import VectorStore
from langchain_core.runnables import RunnableLambda

mock_llm = RunnableLambda(lambda x: "Hypothetical passage text.")

def failing_llm_func(x):
    raise Exception("API Timeout")

mock_failing_llm = RunnableLambda(failing_llm_func)

def test_hybrid_search_no_hyde():
    store = VectorStore()
    docs = [Document(page_content="Target content", metadata={"source": "test"})]
    store.index_documents(docs)
    
    retriever = AdvancedRetriever(use_hyde=False, vector_store=store)
    results = retriever.get_relevant_documents("Target")
    
    assert len(results) > 0
    assert "Target" in results[0].page_content

def test_hybrid_search_with_hyde_success():
    store = VectorStore()
    docs = [Document(page_content="Target content", metadata={"source": "test"})]
    store.index_documents(docs)
    
    llm = mock_llm
    # Since prompt | llm | parser creates a chain, we need to mock the chain invoke
    retriever = AdvancedRetriever(use_hyde=True, vector_store=store, llm=llm)
    retriever.hyde_chain = MagicMock()
    retriever.hyde_chain.invoke.return_value = "Hypothetical context generated by LLM"
    
    results = retriever.get_relevant_documents("Target")
    assert len(results) > 0
    assert retriever.hyde_chain.invoke.called

def test_hybrid_search_hyde_fallback():
    store = VectorStore()
    docs = [Document(page_content="Target content", metadata={"source": "test"})]
    store.index_documents(docs)
    
    # Simulate LLM crash
    retriever = AdvancedRetriever(use_hyde=True, vector_store=store)
    retriever.hyde_chain = MagicMock()
    retriever.hyde_chain.invoke.side_effect = Exception("API Offline")
    
    # Should catch exception and fallback to base query without crashing
    results = retriever.get_relevant_documents("Target")
    assert len(results) > 0

def test_hybrid_search_empty_base_docs():
    store = VectorStore()
    retriever = AdvancedRetriever(use_hyde=False, vector_store=store)
    
    # No documents indexed, should gracefully return empty list
    results = retriever.get_relevant_documents("Nonexistent")
    assert results == []
